export const SET_WORKBOOK_VALUE = "SET_WORKBOOK_VALUE";

export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const EDIT_TEAM_MEMBER = "EDIT_TEAM_MEMBER";
export const DELETE_TEAM_MEMBER = "DELETE_TEAM_MEMBER";

export const ADD_BUSINESS_QUESTION = "ADD_BUSINESS_QUESTION";
export const EDIT_BUSINESS_QUESTION = "EDIT_BUSINESS_QUESTION";
export const DELETE_BUSINESS_QUESTION = "DELETE_BUSINESS_QUESTION";

export const ADD_CARD = "ADD_CARD";
export const EDIT_CARD = "EDIT_CARD";
export const DELETE_CARD = "DELETE_CARD";
